version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: ${CONTAINER_NAME}
    ports:
      - ${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
